### ISSUE TITLE
Compatibility check to js-controller 3.3 and Admin5 React UI

### ISSUE THREAD

**Issue by ioBrokerChecker** [Scrounger/ioBroker.linkeddevices#67] opened 2021-05-05 16:37 UTC
Dear Adapter developer,

with js-controller 3.2 and js-controller 3.3 some additional checks were added to make sure that created objects match to the specifications and also written state values match to the object definition.

If something is not correct this is logged as 'warning' or 'info' log.

Please take the time to verify your adapter by ideally starting with a fresh instance and do some actions and verify the log. If you see a warn log there from these checks please adjust the adapter and fix the relevant cases.

For questions please refer to https://github.com/ioBroker/ioBroker.js-controller/issues/1301 

Additionally we are preparing Admin 5 which will have a completely rewritten UI. Please install Admin 5, activate that new UI and verify that the configuration of you adapter works as expected also there.

More informations on Admin 5 can be found in Forum https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui 

Please close the issue after you checked it.

Thank you very much for your support!

**Comment by tmycgn** [comment] 2021-06-05 09:51
Adapter constantly throws warnings:

_Read-only state "linkeddevices.0.xxxxxxxxxxxxx" has been written without ack-flag with value "xxxxxxxx"_

JS controller changes:
https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md
Version 3.3.1: "if state is read only and we get ack false -> not allowed"

**Comment by Scrounger** [comment] 2021-06-09 09:56
@tmycgn 

how do you write the value to the datapoints? If this is done by an other adapter, then the ack flag is not set by this adapter -> please report it there.

**Comment by tmycgn** [comment] 2021-06-09 10:48
@Scrounger 

I am a normal end user and use the adapter by default. The warning is thrown by the adapter as attached: 

![image](https://user-images.githubusercontent.com/82310796/121341370-e26f1800-c920-11eb-9722-ca4cd0c2e14f.png)

Are the write parameters (missing ack-flag) passed on from the source adapter?

**Comment by Apollon77** [comment] 2021-06-09 11:36
@Scrounger when the reporting adapter is linkeddevices then normally the write comes also from this adapter. If ir would be a javascript script then that adapter would  be shown

**Comment by Scrounger** [comment] 2021-06-09 13:03
> Are the write parameters (missing ack-flag) passed on from the source adapter?

Correct, linkeddevices just mirror the datapoint, if the datapoint is readonly and changed without ack = true flag, then the ack flag will also not set at linkeddevices object. But in this case there must be an other log message from the source adapter - as @Apollon77 described.
Please provide the raw data of this datapoint and the raw data of parent object

@Apollon77 
totaly agree, normally linkeddevices never writes states by its own. It is always triggered by an other adapter.
But i have to go deeper to figure out why this happens.

**Comment by tmycgn** [comment] 2021-06-09 15:00
In this case it is a replication of the radar2 adapter. If I understood you both correctly, then the problem is here and not with linkeddevices. 

Attached the raw data of the object "linkeddevices.0.Anwesenheit.Wohnzimmer.Thomas_Presence"

```
{
  "type": "state",
  "common": {
    "name": "Anwesenheit Wohnzimmer Thomas_Presence",
    "read": true,
    "write": false,
    "state": "state",
    "role": "value",
    "type": "boolean",
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "parentId": "radar2.0.Thomas_Wearable",
        "parentType": "boolean",
        "isLinked": true
      },
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": 0,
        "maxLength": 10,
        "retention": 0,
        "changesRelogInterval": "3600",
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      },
      "telegram.0": {
        "enabled": true,
        "readOnly": true,
        "writeOnly": false,
        "report": true,
        "alias": "",
        "onStatus": "",
        "offStatus": "",
        "onCommand": "",
        "offCommand": "",
        "onlyTrue": false,
        "buttons": 3
      }
    },
    "icon": "linkeddevices_small.png",
    "desc": "Created by linkeddevices"
  },
  "native": {
    "radar2": {
      "name": "Thomas_Wearable",
      "ip": [],
      "bluetooth": [
        "xxxxxxxx",
        "xxxxxxxx"
      ],
      "enabled": -1,
      "id": "Thomas_Wearable",
      "type": "BT",
      "btVendor": "xxxxxxxx",
      "lasthere": "2021-06-09T14:51:54.138Z"
    }
  },
  "from": "system.adapter.linkeddevices.0",
  "user": "system.user.admin",
  "ts": 1623250562344,
  "_id": "linkeddevices.0.Anwesenheit.Wohnzimmer.Thomas_Presence",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  }
}
```

**Comment by Scrounger** [comment] 2021-06-09 16:26
@tmycgn 
data seems to be ok.
Please set the adapter to debug (Admin -> instances -> enable export mode -> choose debug from dropdown).
Now if the warn message is shown again, please post the log. Some entries before or after there must be a debug message where you can see which ack state is send from the radar2 adapter.

**Comment by tmycgn** [comment] 2021-06-11 06:18
@Scrounger 
Does this help as info? According to this, no ack state is sent from radar2 either.

![image](https://user-images.githubusercontent.com/82310796/121639809-61815f00-ca8d-11eb-89c9-4cd4436f8e50.png)

**Comment by Apollon77** [comment] 2021-06-11 09:19
Aahhhh @tmycgn Then the root case seems to be radar2 ... Once fixed there it should be also fixed in linjkeddevices ... so I would foxus on radar2 for now

**Comment by tmycgn** [comment] 2021-06-11 09:21
Ok, learned something again and maybe it will help others ;)
Thanks for the support @Scrounger @Apollon77 and we can close the issue now.

**Comment by Scrounger** [comment] 2021-06-11 20:13
Then my assumption was correct, it is clear from your log.
Issue I still leave open, because I still have to make a few test myself

**Comment by apartmedia** [comment] 2021-09-01 23:54
@Scrounger @Apollon77 May I ask one question to understand things better, as I‘m pretty new to ioBroker.
I read a lot of stuff on the forum regarding the new admin 5 changes when it comes to user-defined structures and the new admin checkings for non existing parents/folders in object hierarchies. If I understood the discussion correctly, everybody strongly recommend to not create own structures and datapoints inside adapter namespaces. This should only be done in 0_userdata (and for historical reasons is accepted also in javascript.0). Shouldn‘t then alias.0 be the right location to link to datapoints from device adapters?
If that’s true, what is the advantage of using this one here and having custom structures inside an adapter namespace instead of using alias.0 for this purpose?
I might get something totally wrong in cause of my missing deeper knowledge of ioBroker and how their Adapters and datapoints stuff work exactly.
What I read about it was [this forum topic](https://forum.iobroker.net/topic/46814/admin5-ich-kann-keine-objekte-mehr-manuell-anlegen)…
Would be nice if you can explain the differences/advantages of this adapter and/or using alias.0 for linking datapoints.

**Comment by Apollon77** [comment] 2021-09-02 07:40
In fact (and very important this is MY personal point of view!): The adapter offered a features like the Alias Feature way before the alias feature was added to core and in admin. IBecause I personally do not use it I can not tell anything about the befeits of linkeddevices over alias in detail ...

**Comment by DocGame69** [comment] 2021-09-09 08:24
Ich habe mich schon zig mal mit Alias beschäftigt und komme einfach nicht klar.
Für mich war (ist) LinkedDevice ideal und ich habe wirklich alle States meines Systems drin.
Irgendwann würde ich vielleicht doch auf die neue UI umsteigen wollen. Der einzige Grund dies nicht zu tun ist die Unverträglichkeit zu LinkedDevice. Ich verfolge seit Monaten die Diskussion (wobei ich nur Bahnhof verstehe), sehe aber keine Fortschritte.
Muss man die Hoffnung aufgeben oder ist noch Bewegung drin?

**Comment by Scrounger** [comment] 2021-09-10 17:29
@DocGame69 
Also der Adapter funktioniert doch mit Admin 5.
Das einzige was aktuell noch nicht geht, ist die Konfiguration. Aber hier kann man sich behelfen indem man im Admin temporär die alte Gui aktiviert. Ich warte aktuell noch auf @GermanBluefox das er beim Admin Custom Dialog etwas implementiert damit ich die Gui auch umstellen kann, mehr dazu findet ihr hier:
https://github.com/ioBroker/ioBroker.admin/issues/692#issuecomment-857472871

**Comment by Scrounger** [comment] 2022-04-25 07:51
done

**Closed by Scrounger** 2022-04-25 07:51 UTC
